{
  config,
  lib,
  pkgs,
  ...
}: {
  imports = [
    # Users
    ../common/users/xokdvium

    # Common configuration
    ../common/global
    ../common/optional/i3

    # Autogenerated hardware config
    ./hardware-configuration.nix
  ];

  boot = {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
  };

  networking = rec {
    hostName = "nanospark";
    hostId = builtins.substring 0 8 (builtins.hashString "sha512" hostName);
    networkmanager.enable = true;
  };

  system.stateVersion = "23.05"; # Did you read the comment?
}
