{
  config,
  lib,
  pkgs,
  ...
}: {
  imports = [
    # Autogenerated hardware config
    ./hardware-configuration.nix
  ];

  boot = {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
  };

  networking = rec {
    hostName = "nanospark";
    hostId = builtins.substring 0 8 (builtins.hashString "sha512" hostName);
    networkmanager.enable = true;
  };
}
