keys:
  - &xokdvium 158A6F530EA202E5F651611314FAEA63448E1DF9
  - &vivobook 461FC9486BAC2D0E85CFF91DA81FF310CADF2F71
  - &nebulinx 0D00A7D80E5D328F1B4E6A4AB83AF36F31276991
creation_rules:
  - path_regex: ^hosts/machines/nebulinx/secrets.yaml$
    key_groups:
      - pgp:
          - *xokdvium
          - *nebulinx
  - path_regex: ^hosts/machines/vivobook/secrets.yaml$
    key_groups:
      - pgp:
          - *xokdvium
          - *vivobook
  - path_regex: ^secrets/syncoid/secrets.yaml$
    key_groups:
      - pgp:
          - *xokdvium
          - *nebulinx
          - *vivobook
  - path_regex: ^secrets/github/secrets.yaml$
    key_groups:
      - pgp:
          - *xokdvium
          - *nebulinx
          - *vivobook
